### ISSUE TITLE
Scan Barcode Page - Issue with Title Display

### ISSUE THREAD

**Issue by jz8942** [UOA-COMPCSI778-LY-2023/sparklingapp#59]
![Scanning Barcode](https://github.com/UOA-COMPCSI778-LY-2023/sparklingapp/assets/141084302/f80f1417-19c7-4448-a9c8-0ae521714dff)

At the top should diaplay “Scan Barcode” - Font size 24, one line below display as "Record the Food You are Eating" - Font size 12.

**Comment by UoAres** [comment]
<img width="374" alt="截屏2024-02-02 上午11 01 51" src="https://github.com/UOA-COMPCSI778-LY-2023/sparklingapp/assets/126945634/1d127116-a940-46d4-a5a1-5a5191458842">
