### ISSUE TITLE
Scan Barcode Page - Creat two different tabs

### ISSUE THREAD

**Issue by jz8942** [UOA-COMPCSI778-LY-2023/sparklingapp#60]
![Scanning Barcode](https://github.com/UOA-COMPCSI778-LY-2023/sparklingapp/assets/141084302/83063de7-c1d5-44be-9f34-75590e497546)

Add two tabs - "Scanning" & "Food Detection"

"Scanning" will only perform barcode scanning function
"Food Detection" will call Google Gemini to provide Healthy Tips

When the tab is activated, it should be highlighted with a blueline underneath the tab.

**Comment by UoAres** [comment]
<img width="373" alt="截屏2024-02-02 上午10 40 47" src="https://github.com/UOA-COMPCSI778-LY-2023/sparklingapp/assets/126945634/b1566d74-e5ff-41d3-9ec7-d9bd95188ddc">
<img width="375" alt="截屏2024-02-02 上午10 41 00" src="https://github.com/UOA-COMPCSI778-LY-2023/sparklingapp/assets/126945634/74530e82-585b-43ad-9079-2edf2a9cecd9">
