### ISSUE TITLE
Scan Barcode Page - Update Back Button

### ISSUE THREAD

**Issue by jz8942** [UOA-COMPCSI778-LY-2023/sparklingapp#61]
![Scanning Barcode](https://github.com/UOA-COMPCSI778-LY-2023/sparklingapp/assets/141084302/32102fc8-b846-4a4c-b302-a2f3f87e8e1a)

Update the back buttom at the top left corner, should display as the photo attached

**Comment by UoAres** [comment]
<img width="372" alt="截屏2024-02-02 上午10 55 50" src="https://github.com/UOA-COMPCSI778-LY-2023/sparklingapp/assets/126945634/2be348fc-96e5-462a-b231-6bba1f41dbec">
