### ISSUE TITLE
Product Details Page - Total Sugar Caculation Issue

### ISSUE THREAD

**Issue by jz8942** [UOA-COMPCSI778-LY-2023/sparklingapp#62]
![Product Details](https://github.com/UOA-COMPCSI778-LY-2023/sparklingapp/assets/141084302/e0b7996f-fa8c-4c3c-bd21-6b1ac418ae7b)

Total Sugar should be calculated as ("APP-Serving Qty" / "DB-serving_qty") * ("DB-nutriments:Sugars")

**Comment by UoAres** [comment]
<img width="372" alt="截屏2024-02-02 下午12 14 02" src="https://github.com/UOA-COMPCSI778-LY-2023/sparklingapp/assets/126945634/9a5e7385-18bd-4718-8340-fa8a5a2bc1cb">

The total amount of sugar that needs to be shown in the product detail page is not the total amount of sugar contained in the product, but the total amount of sugar after the user selects how many servings. The amount of sugar recorded in nutriments is not the amount of a single food item, but the amount of a serving. And the value of serving_qty is how many units of food are in a serving. The amount equivalent to a single food item is equal to the serving divided by the value of serving_qty. Finally, the value of total sugar shown on the interface is the amount of individual food items multiplied by how many units of food items the user has selected. Also, when the user selects the quantity, they are not selecting how much serving was consumed, but how many units of food were consumed.
