### ISSUE TITLE
Product Details Page - the number of tea spoons

### ISSUE THREAD

**Issue by jz8942** [UOA-COMPCSI778-LY-2023/sparklingapp#63]
![Dominos+Sugar](https://github.com/UOA-COMPCSI778-LY-2023/sparklingapp/assets/141084302/f3431a2d-5fad-4db8-a0d1-19333be1a332)

https://www.canr.msu.edu/news/how_to_convert_grams_of_sugars_into_teaspoons

According the reference above:
The number of tea spoons = Total Sugar / 4

**Comment by UoAres** [comment]
<img width="372" alt="截屏2024-02-02 上午11 06 16" src="https://github.com/UOA-COMPCSI778-LY-2023/sparklingapp/assets/126945634/964d81ec-ee9a-4280-8cc1-f0aff7f3d6da">
