### ISSUE TITLE
Product Details Page - Remove Serving Size

### ISSUE THREAD

**Issue by jz8942** [UOA-COMPCSI778-LY-2023/sparklingapp#64]
![Product Details](https://github.com/UOA-COMPCSI778-LY-2023/sparklingapp/assets/141084302/ebf2a16c-f9d8-4e8c-8755-190235e0b62e)

Please remove the "Serving Size" text and the coresponding number. Only Display "serving_qty_unit" attribute from DB, such as Glass, Biscuit and etc

**Comment by UoAres** [comment]
<img width="371" alt="截屏2024-02-02 上午11 18 52" src="https://github.com/UOA-COMPCSI778-LY-2023/sparklingapp/assets/126945634/bb480c88-c68f-4556-9069-1492beb2756b">
