### ISSUE TITLE
Product Details Page - Product Name

### ISSUE THREAD

**Issue by jz8942** [UOA-COMPCSI778-LY-2023/sparklingapp#65]
![Screenshot_20240201_193853](https://github.com/UOA-COMPCSI778-LY-2023/sparklingapp/assets/141084302/e25b5d1a-5f18-422e-979b-be7105a5ad2d)

The Product Name font is too big compares to other tables.
Please update it to the same font size in the intake history page.

**Comment by UoAres** [comment]
<img width="373" alt="截屏2024-02-02 上午11 11 28" src="https://github.com/UOA-COMPCSI778-LY-2023/sparklingapp/assets/126945634/a3eded0e-a57e-4a66-be36-6491680a1e9c">

The font size switches to a fixed size of 16, no longer following the default setting of the mobile phone system.

**Comment by UoAres** [comment]
<img width="372" alt="截屏2024-02-02 上午11 13 33" src="https://github.com/UOA-COMPCSI778-LY-2023/sparklingapp/assets/126945634/99f74e08-11f9-4dc9-8400-0a9ddac48bd6">
