### ISSUE TITLE
Product Details Page - Nutrition Table been covered by Confirm and Cancel Button

### ISSUE THREAD

**Issue by jz8942** [UOA-COMPCSI778-LY-2023/sparklingapp#66]
![Screenshot_20240201_193853](https://github.com/UOA-COMPCSI778-LY-2023/sparklingapp/assets/141084302/eec29561-0ee0-4eae-a544-6458f02e09f8)

The nutrition table, when it is scrolled to the buttom of the screen, some nutriments are covered by Confirm and Cancel button.

Please make sure the nutrition info is not covered.

**Comment by UoAres** [comment]
<img width="371" alt="截屏2024-02-02 上午11 37 17" src="https://github.com/UOA-COMPCSI778-LY-2023/sparklingapp/assets/126945634/87b9ae18-4e54-471e-98d9-a45d2602e47d">
