### ISSUE TITLE
Product Details Page - section for equals to tea sppons of sugar

### ISSUE THREAD

**Issue by jz8942** [UOA-COMPCSI778-LY-2023/sparklingapp#67]
![Screenshot 2024-02-02 at 11 10 36 AM](https://github.com/UOA-COMPCSI778-LY-2023/sparklingapp/assets/141084302/1c11d0cd-2aee-4e30-8cc3-5023aafb0eee)

The highlighted section does't display the full text, can you make sure it does, please.

**Comment by UoAres** [comment]
<img width="371" alt="截屏2024-02-02 上午11 25 41" src="https://github.com/UOA-COMPCSI778-LY-2023/sparklingapp/assets/126945634/ee7e0de9-d967-43a1-8f64-a7cc24101b1e">
