### ISSUE TITLE
Product Details Page - Update Back Button

### ISSUE THREAD

**Issue by jz8942** [UOA-COMPCSI778-LY-2023/sparklingapp#68]
![Product Details](https://github.com/UOA-COMPCSI778-LY-2023/sparklingapp/assets/141084302/f54e62bb-0aff-4602-8489-57e7cf5223df)

Please change the back button to match the photo attached, blue button with white arrow.

**Comment by UoAres** [comment]
<img width="369" alt="截屏2024-02-02 上午11 23 39" src="https://github.com/UOA-COMPCSI778-LY-2023/sparklingapp/assets/126945634/a548f295-e4e5-4263-b37b-c5e5a06847fd">
