### ISSUE TITLE
Product Details Page - Adjust Text of serving_qty_unit

### ISSUE THREAD

**Issue by jz8942** [UOA-COMPCSI778-LY-2023/sparklingapp#69]
![Screenshot 2024-02-02 at 12 40 32 PM](https://github.com/UOA-COMPCSI778-LY-2023/sparklingapp/assets/141084302/3355f3ae-6a89-4711-ab86-22b8be08fc96)

Please Adjust Text of serving_qty_unit, centre to the Serving Qty 1, leave a space gap, First letter capital, .

**Comment by UoAres** [comment]
<img width="372" alt="截屏2024-02-02 下午12 50 41" src="https://github.com/UOA-COMPCSI778-LY-2023/sparklingapp/assets/126945634/893d05b4-943c-4a61-b78d-29e8872ab43c">
